# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine
WORKDIR /app

# Copy package files for dependency installation
COPY package*.json ./

# Install dependencies without running scripts
RUN npm install --ignore-scripts

# Copy the rest of the application source
COPY . ./

# Install TypeScript Node types and build the project
RUN npm install --save-dev @types/node && npm run build

# Start the MCP server
CMD ["node", "dist/index.js"]
